export const availableBlocks = [
    'alert',
    'cta',
    'informations',
    'pushes',
    'datas',
    'map',
    'quote',
    'latest',
    'editorial',
    'embed',
    'faq',
    'figure',
    'gallery',
    'images',
    // 'instagram',
    'paragraph',
    'selectedexpertises',
    'selectedoffices',
    'selectedposts',
    'selectedpersons',
    'selectedpublications',
    'title'
];